export const dummyPlaylistData = [
    {
        id: 1,
        name: 'History',
        type: 'default',
        parentUser: 1,
    },
    {
        id: 2,
        name: 'Liked',
        type: 'default',
        parentUser: 1,
    },
    {
        id: 3,
        name: 'Watch Later',
        type: 'default',
        parentUser: 1,
    },
    {
        id: 4,
        name: 'History',
        type: 'default',
        parentUser: 2,
    },
    {
        id: 5,
        name: 'Liked',
        type: 'default',
        parentUser: 2,
    },
    {
        id: 6,
        name: 'Watch Later',
        type: 'default',
        parentUser: 2,
    },
    {
        id: 7,
        name: 'History',
        type: 'default',
        parentUser: 3,
    },
    {
        id: 8,
        name: 'Liked',
        type: 'default',
        parentUser: 3,
    },
    {
        id: 9,
        name: 'Watch Later',
        type: 'default',
        parentUser: 3,
    },
    {
        id: 10,
        name: 'History',
        type: 'default',
        parentUser: 4,
    },
    {
        id: 11,
        name: 'Liked',
        type: 'default',
        parentUser: 4,
    },
    {
        id: 12,
        name: 'Watch Later',
        type: 'default',
        parentUser: 4,
    },
    {
        id: 13,
        name: 'History',
        type: 'default',
        parentUser: 5,
    },
    {
        id: 14,
        name: 'Liked',
        type: 'default',
        parentUser: 5,
    },
    {
        id: 15,
        name: 'Watch Later',
        type: 'default',
        parentUser: 5,
    },
]